/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traitementimage;

import java.awt.AWTException;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Point;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.UIManager;


/**
 *
 * @author danilecx
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    private boolean paletteEnabled, roiEnabled;
    private Point mousePressed, mouseReleased;
    
    public mainFrame() {
        initComponents();
        getContentPane().setBackground(new Color(34,40,49));
        paletteEnabled = roiEnabled = false;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        imgSrc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        imgFin = new javax.swing.JLabel();
        depLabel = new javax.swing.JLabel();
        finLabel = new javax.swing.JLabel();
        leftArrowLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        loadImage = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        paletteLabel = new javax.swing.JLabel();
        srcColorPalette = new javax.swing.JLabel();
        endColorPalette = new javax.swing.JLabel();
        sizeXField = new javax.swing.JTextField();
        sizeYField = new javax.swing.JTextField();
        roiLabel = new javax.swing.JLabel();
        paletteLabel1 = new javax.swing.JLabel();
        paletteLabel2 = new javax.swing.JLabel();
        extractionYField = new javax.swing.JTextField();
        extractionXField = new javax.swing.JTextField();
        expansionXField = new javax.swing.JTextField();
        expansionYField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(34, 40, 49));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(34, 40, 49));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(520, 520));

        imgSrc.setBackground(new java.awt.Color(57, 62, 70));
        imgSrc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgSrc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 62, 70)));
        imgSrc.setOpaque(true);
        imgSrc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgSrcMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgSrcMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                imgSrcMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(imgSrc);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(520, 520));

        imgFin.setBackground(new java.awt.Color(57, 62, 70));
        imgFin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 62, 70)));
        imgFin.setOpaque(true);
        jScrollPane2.setViewportView(imgFin);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        depLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        depLabel.setForeground(new java.awt.Color(238, 238, 238));
        depLabel.setText("Image de départ");
        jPanel2.add(depLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        finLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        finLabel.setForeground(new java.awt.Color(238, 238, 238));
        finLabel.setText("Image de fin");
        jPanel2.add(finLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        leftArrowLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitementimage/images/left-arrow.png"))); // NOI18N
        leftArrowLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftArrowLabelMouseClicked(evt);
            }
        });
        jPanel2.add(leftArrowLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 250, -1, -1));

        jPanel3.setBackground(new java.awt.Color(57, 62, 70));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitementimage/images/loadImage.png"))); // NOI18N
        loadImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadImageMouseClicked(evt);
            }
        });
        jPanel3.add(loadImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(238, 238, 238));
        jSeparator1.setForeground(new java.awt.Color(238, 238, 238));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 20, 190));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 238, 238));
        jLabel5.setText("Taille");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        paletteLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        paletteLabel.setForeground(new java.awt.Color(238, 238, 238));
        paletteLabel.setText("Extraction");
        paletteLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paletteLabelMouseClicked(evt);
            }
        });
        jPanel3.add(paletteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, -1, -1));

        srcColorPalette.setBackground(new java.awt.Color(255, 255, 255));
        srcColorPalette.setOpaque(true);
        jPanel3.add(srcColorPalette, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 40, 20));

        endColorPalette.setBackground(new java.awt.Color(255, 0, 0));
        endColorPalette.setOpaque(true);
        endColorPalette.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endColorPaletteMouseClicked(evt);
            }
        });
        jPanel3.add(endColorPalette, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 40, 20));

        sizeXField.setForeground(new java.awt.Color(238, 238, 238));
        sizeXField.setText("x");
        sizeXField.setCaretColor(new java.awt.Color(238, 238, 238));
        sizeXField.setOpaque(false);
        sizeXField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeXFieldActionPerformed(evt);
            }
        });
        jPanel3.add(sizeXField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 40, -1));

        sizeYField.setForeground(new java.awt.Color(238, 238, 238));
        sizeYField.setText("y");
        sizeYField.setCaretColor(new java.awt.Color(238, 238, 238));
        sizeYField.setOpaque(false);
        sizeYField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeYFieldActionPerformed(evt);
            }
        });
        jPanel3.add(sizeYField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 40, -1));

        roiLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        roiLabel.setForeground(new java.awt.Color(238, 238, 238));
        roiLabel.setText("ROI");
        roiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roiLabelMouseClicked(evt);
            }
        });
        jPanel3.add(roiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        paletteLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        paletteLabel1.setForeground(new java.awt.Color(238, 238, 238));
        paletteLabel1.setText("Palette");
        paletteLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paletteLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(paletteLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        paletteLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        paletteLabel2.setForeground(new java.awt.Color(238, 238, 238));
        paletteLabel2.setText("Expansion");
        paletteLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paletteLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(paletteLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, -1));
        jPanel3.add(extractionYField, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, 40, -1));
        jPanel3.add(extractionXField, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 40, -1));

        expansionXField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expansionXFieldActionPerformed(evt);
            }
        });
        jPanel3.add(expansionXField, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 40, -1));

        expansionYField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expansionYFieldActionPerformed(evt);
            }
        });
        jPanel3.add(expansionYField, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 40, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 1080, 214));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadImageMouseClicked
        JFileChooser fc = new JFileChooser();
        int result = fc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String sname = file.getAbsolutePath();
            BufferedImage img = null;
            try {
                img = ImageIO.read(new File(sname));
            } catch (IOException e) {
                e.printStackTrace();
            }
            sizeXField.setText(String.valueOf(img.getWidth()));
            sizeYField.setText(String.valueOf(img.getHeight()));
            imgSrc.setIcon(new ImageIcon(img));
            imgFin.setIcon(new ImageIcon(img));
        }  
    }//GEN-LAST:event_loadImageMouseClicked

    private void sizeXFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeXFieldActionPerformed
        updateImageSize();
    }//GEN-LAST:event_sizeXFieldActionPerformed

    private void sizeYFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeYFieldActionPerformed
        updateImageSize();
    }//GEN-LAST:event_sizeYFieldActionPerformed

    private void paletteLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paletteLabelMouseClicked
        if(paletteEnabled)
        {
            paletteLabel.setForeground(new Color(238, 238, 238));
            paletteEnabled = false;
        }
        else
        {
            paletteLabel.setForeground(new Color(0, 173, 181));
            paletteEnabled = true;
        }
    }//GEN-LAST:event_paletteLabelMouseClicked

    private void imgSrcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSrcMouseClicked
        if(paletteEnabled)
        {
            Point loc = evt.getLocationOnScreen();
            
            Robot robot;
            Color color = Color.WHITE;
            try {
                robot = new Robot();
                color = robot.getPixelColor((int)loc.getX(), (int)loc.getY());
            } catch (AWTException ex) {
                Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            srcColorPalette.setBackground(color);

            replaceColor();
        }
    }//GEN-LAST:event_imgSrcMouseClicked

    private void endColorPaletteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endColorPaletteMouseClicked
        Color newColor = JColorChooser.showDialog(null, "Choose a color", Color.RED);
        endColorPalette.setBackground(newColor);
        if(paletteEnabled)
            replaceColor();
    }//GEN-LAST:event_endColorPaletteMouseClicked

    private void leftArrowLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftArrowLabelMouseClicked
        ImageIcon icon = (ImageIcon) imgFin.getIcon();
        BufferedImage img = getBufferedImage(icon);
        Image scaledImg = img.getScaledInstance(icon.getIconWidth(), icon.getIconHeight(), Image.SCALE_SMOOTH);
        imgSrc.setIcon(new ImageIcon(scaledImg));
    }//GEN-LAST:event_leftArrowLabelMouseClicked

    private void roiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roiLabelMouseClicked
        if(roiEnabled)
        {
            roiLabel.setForeground(new Color(238, 238, 238));
            roiEnabled = false;
        }
        else
        {
            roiLabel.setForeground(new Color(0, 173, 181));
            roiEnabled = true;
            
        }
    }//GEN-LAST:event_roiLabelMouseClicked

    private void imgSrcMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSrcMouseReleased
       if(roiEnabled)
       {
           mouseReleased = evt.getPoint();
           
           
           ImageIcon icon = (ImageIcon) imgSrc.getIcon();
           BufferedImage fullImage = getBufferedImage(icon);
           int x, y, width, height;
           x = (mousePressed.getX() < mouseReleased.getX())? (int)mousePressed.getX() : (int)mouseReleased.getX();
           width = (int) Math.abs(mousePressed.getX() - mouseReleased.getX());
           y = (mousePressed.getY() < mouseReleased.getY())? (int)mousePressed.getY() : (int)mouseReleased.getY();
           height = (int) Math.abs(mousePressed.getY() - mouseReleased.getY());
           if(fullImage.getWidth() < 512)
                x -= 256-fullImage.getWidth()/2;

           if(fullImage.getHeight()< 512)
                y -= 256-fullImage.getWidth()/2;
           
           
           BufferedImage newImage = fullImage.getSubimage(x, y, width, height);
           imgFin.setIcon(new ImageIcon(newImage));
           
       }
    }//GEN-LAST:event_imgSrcMouseReleased

    private void imgSrcMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSrcMousePressed
        if(roiEnabled)
        {
            mousePressed = evt.getPoint();
        }
    }//GEN-LAST:event_imgSrcMousePressed

    private void paletteLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paletteLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_paletteLabel1MouseClicked

    private void paletteLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paletteLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_paletteLabel2MouseClicked

    private void expansionXFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expansionXFieldActionPerformed
        bilinearInterpolation();
    }//GEN-LAST:event_expansionXFieldActionPerformed

    private void expansionYFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expansionYFieldActionPerformed
        bilinearInterpolation();
    }//GEN-LAST:event_expansionYFieldActionPerformed

    private void updateImageSize()
    {
        ImageIcon icon = (ImageIcon) imgSrc.getIcon();
        BufferedImage img = getBufferedImage(icon);
        Image scaledImg = img.getScaledInstance(Integer.parseInt(sizeXField.getText()), Integer.parseInt(sizeYField.getText()), Image.SCALE_SMOOTH);
        imgFin.setIcon(new ImageIcon(scaledImg));
        
    }
    
    private void replaceColor()
    {
        int inputRGB = srcColorPalette.getBackground().getRGB();
        int outputRGB = endColorPalette.getBackground().getRGB();
        ImageIcon icon = (ImageIcon) imgSrc.getIcon();
        BufferedImage img = getBufferedImage(icon);
        
        BufferedImage argbImage = new BufferedImage(img.getWidth(), img.getHeight(), BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = argbImage.createGraphics();
        g.drawImage(img, 0, 0, null);
        g.dispose();
        
        for (int i = 0; i < img.getHeight(); i++) {
            for (int j = 0; j < img.getWidth(); j++) {
                if(img.getRGB(i, j) == inputRGB)
                {
                    argbImage.setRGB(i, j, outputRGB);
                }
            }
        }
        
        imgFin.setIcon(new ImageIcon(argbImage));
    }
    
    private BufferedImage getBufferedImage(ImageIcon icon)
    {
        BufferedImage bi = new BufferedImage(
        icon.getIconWidth(),
        icon.getIconHeight(),
        BufferedImage.TYPE_INT_RGB);
        
        Graphics g = bi.createGraphics();
        // paint the Icon to the BufferedImage.
        icon.paintIcon(null, g, 0,0);
        g.dispose();
        return bi;
    }
    
    private void bilinearInterpolation()
    {
        String x, y;
        ImageIcon icon = (ImageIcon) imgSrc.getIcon();
        BufferedImage img = getBufferedImage(icon);
        x = this.expansionXField.getText();
        y = this.expansionYField.getText();
        this.imgFin.setIcon(new ImageIcon(BilinearInterpolation.scale(img, Float.parseFloat(x) , Float.parseFloat(y))));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainFrame frame = new mainFrame();
                frame.setLocationRelativeTo(null); // Center of the screen
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel depLabel;
    private javax.swing.JLabel endColorPalette;
    private javax.swing.JTextField expansionXField;
    private javax.swing.JTextField expansionYField;
    private javax.swing.JTextField extractionXField;
    private javax.swing.JTextField extractionYField;
    private javax.swing.JLabel finLabel;
    private javax.swing.JLabel imgFin;
    private javax.swing.JLabel imgSrc;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel leftArrowLabel;
    private javax.swing.JLabel loadImage;
    private javax.swing.JLabel paletteLabel;
    private javax.swing.JLabel paletteLabel1;
    private javax.swing.JLabel paletteLabel2;
    private javax.swing.JLabel roiLabel;
    private javax.swing.JTextField sizeXField;
    private javax.swing.JTextField sizeYField;
    private javax.swing.JLabel srcColorPalette;
    // End of variables declaration//GEN-END:variables
}
