/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traitementimage;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 *
 * @author danilecx
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selectIcon = new javax.swing.JLabel();
        selectPoint1 = new javax.swing.JLabel();
        selectPoint2 = new javax.swing.JLabel();
        loadImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        imgFin = new javax.swing.JLabel();
        imgSrc = new javax.swing.JLabel();
        depLabel = new javax.swing.JLabel();
        finLabel = new javax.swing.JLabel();
        arrowLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(34, 40, 49));

        jPanel2.setBackground(new java.awt.Color(34, 40, 49));

        jPanel3.setBackground(new java.awt.Color(57, 62, 70));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 117, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("Extraction");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 124, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("00");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 124, -1, -1));
        jPanel3.add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 149, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("Expansion");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 238, 238));
        jLabel4.setText("00");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 156, -1, -1));

        selectIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitementimage/images/selectionROI.png"))); // NOI18N
        selectIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectIconMouseClicked(evt);
            }
        });
        jPanel3.add(selectIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        selectPoint1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        selectPoint1.setForeground(new java.awt.Color(238, 238, 238));
        selectPoint1.setText("X1:     Y1:");
        jPanel3.add(selectPoint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        selectPoint2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        selectPoint2.setForeground(new java.awt.Color(238, 238, 238));
        selectPoint2.setText("X2:     Y2:");
        jPanel3.add(selectPoint2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        loadImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitementimage/images/loadImage.png"))); // NOI18N
        loadImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadImageMouseClicked(evt);
            }
        });
        jPanel3.add(loadImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.setBackground(null);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgFin.setBackground(new java.awt.Color(57, 62, 70));
        imgFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 62, 70)));
        jPanel1.add(imgFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 500, 437));

        imgSrc.setBackground(new java.awt.Color(57, 62, 70));
        imgSrc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 62, 70)));
        jPanel1.add(imgSrc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, 437));

        depLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        depLabel.setForeground(new java.awt.Color(238, 238, 238));
        depLabel.setText("Image de départ");
        jPanel1.add(depLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        finLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        finLabel.setForeground(new java.awt.Color(238, 238, 238));
        finLabel.setText("Image de fin");
        jPanel1.add(finLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        arrowLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traitementimage/images/left-arrow.png"))); // NOI18N
        jPanel1.add(arrowLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadImageMouseClicked
        JFileChooser fc = new JFileChooser();
        int result = fc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String sname = file.getAbsolutePath();
            BufferedImage img = null;
            try {
                img = ImageIO.read(new File(sname));
            } catch (IOException e) {
                e.printStackTrace();
            }
            Image dimg = img.getScaledInstance(imgSrc.getWidth(), imgSrc.getHeight(), Image.SCALE_SMOOTH);
            imgSrc.setIcon(new ImageIcon(dimg));
            imgFin.setIcon(new ImageIcon(dimg));
        }  
    }//GEN-LAST:event_loadImageMouseClicked

    private void selectIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectIconMouseClicked
        new RegionSelectorListener(this.imgSrc);
    }//GEN-LAST:event_selectIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrowLabel;
    private javax.swing.JLabel depLabel;
    private javax.swing.JLabel finLabel;
    private javax.swing.JLabel imgFin;
    private javax.swing.JLabel imgSrc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JLabel loadImage;
    private javax.swing.JLabel selectIcon;
    private javax.swing.JLabel selectPoint1;
    private javax.swing.JLabel selectPoint2;
    // End of variables declaration//GEN-END:variables
}
